apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
  namespace: default
  # `kubectl get pvc` 했을 때 보기 편하게 라벨링
  labels:
    app: ghost
    component: content
spec:
  accessModes:
    # 한 번에 하나의 노드에서만 접근 가능
    - ReadWriteOnce
  resources:
    requests:
      # 부족하면 나중에 늘리기 가능
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-database-pvc
  namespace: default
  labels:
    app: ghost
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
