---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-secret
  namespace: default
spec:
  encryptedData:
    openrouter-api-key: AgCUzfrFFQVltO0zbCe/T7cfBaixyqBZMfSDIYozGFrJWAroPyGxezTj4bh8WycAMpa+ct50Sf1pgSlVlWDu/iMCIctCxFIsR5udTyHg0qEfe0EKeRZdh8Y9SH7AcTlfK8PFljnzq9uKM6zNknsLUw1y+OD76SctFqJPyhKnqVwKq6X875WZnTNJmiq55r8KFQLSIZBD/BjEeiqI4bxb2/ffPzWuc7tzN7LUtsrW5HY6F6EDXx7sGbo9FrXoaX82SFv37bMch/92VXz0EKuxAXM82XyKZKUE7euGHMyJT+7t6OVq/tjnYtWx/sBHouBgR7tYVFJsPKdxcDsOOnoT7lzay1ijI7SnoZPAj/Teulv9Bm/nDSkRhfBLXMWKJLN+3ARZEwmQnWiXjHeveIOHT0VvGYZAAMnjY8BFphn2+Zw5q6eC7f9hg9VZWwitfFPwQJFJB1VSLlcvA+J2/2Kisf9D1A+Y2+yR1VXnRetOZwN8rJo9R017UYFBrN10fK7ogk10S5l5iBM1d4+IUrEHU+1WkB7iq1poNNrY0hWBKLACPPuoAqPOPGy8jdT6CiuLAOQCyHg4AJZDVzy6wBztXpd0oq7wPr+Re/2Jr+ZIDHKndlUiEQSbE4Yo2XZxntEp6F8O/UgyPc5+AdGDqm/ONRLXP1s9YTUjlU53nL849HPBporNrBJo74QEXyyfrXagWxzQAsH9bg4oEW/uYF6TYff40yrWIkp85whrhauwEb7zJh8gJ816Sv8qrIIw9t5kUX8FcWgZgvHtNs2LYjVM3nU5BmC2RU26DNiQ
    webui-secret-key: AgCQbDPutD/xzbv0DU6PAx3NWY02oT35ZY3XWiRJXgnAO+PKJONRWrhy3aW8HOSmfvPwdwSJ9f1R1ZFTaIqpVftQGZfnUuWgRDs95q3L4GLXmmG8RKeo2MtdEsKQt7r2sQYFIcGEw5MzYw9PVULpcv/59e7cgKcw8gSIXczh9uNYINWiO8000w5e07FXeCvF0fsgrJjtpf79xZxHID1CFZJFxWMmR6fh2MhO5LWXGI48Wu+ibQIBMRQtsL9CYAD9TuoT/muC/AczJ+k1oiCsVqtxNzbOFOGPKqjc5Ol5ctMX57hOJ0OvSHxaeWKtlvsM/8dftToYP8LDx4Om3KI6tMnCFB+2A3qlvGUdYy29RYg/nmgPu5Lea8t/NhgYkVrmBeBnqMDXDsDc30JzFWnjAcA9D3GwG9deNYRlabET+5Y++17BInLSOnJx4IGmQylH9HyPsfzurIlmAGMjMeKj7orasz2Lb/xn4NvxrnSsbe1kpWDGZt/dp3mMNJK0NFd6F5YsfVdYDKsEt/NbxSpyzzpCW2JktdJk5iw0Y/DzDAi2nylfl9+3MYdhdz3L5t4K67BhQvRkj9KlF3mvHusJgPKmykCNQQjRG6JJJkn3Ymi4y7H2HygKsoJCxxML+Cmm2Q+eMQjAq9FXZjkX1YukvaaEiZI2D71JSmzMBXulLpocMR/yvtznH10UJbExtxLlYP32aYy/SFQne3paZbZWqiLdIQX4GwggHrq7bsa7RRXiXV4oL9RgKTZA4LxTA438
  template:
    metadata:
      name: openwebui-secret
      namespace: default
    type: Opaque
