apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
  annotations:
    # ArgoCD Image Updater 설정
    argocd-image-updater.argoproj.io/image-list: openwebui=ghcr.io/open-webui/open-webui
    # main 태그의 최신 다이제스트(SHA) 추적
    argocd-image-updater.argoproj.io/openwebui.update-strategy: digest
    # 매주 화요일 00시 체크 (cron: 분 시 일 월 요일, 2=화요일)
    argocd-image-updater.argoproj.io/openwebui.schedule: "0 0 * * 2"
    # ArgoCD parameter override로 관리 (Git 커밋 없음)
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/duchangkim/home-lab.git
    targetRevision: main
    path: applications/openwebui
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
