apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
  annotations:
    # ArgoCD Image Updater 설정
    argocd-image-updater.argoproj.io/image-list: openwebui=ghcr.io/open-webui/open-webui:main
    argocd-image-updater.argoproj.io/openwebui.update-strategy: digest
    argocd-image-updater.argoproj.io/openwebui.schedule: "0 0 * * 2"
    argocd-image-updater.argoproj.io/write-back-method: argocd
    # Kustomize 이미지 업데이트 경로 지정
    argocd-image-updater.argoproj.io/write-back-target: "kustomization"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/duchangkim/home-lab.git
    targetRevision: main
    path: applications/openwebui
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
