apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: default
  labels:
    app: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-db-data
  namespace: default
  labels:
    app: n8n
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
